// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tnvkqwmtcvhuyvgugctb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRudmtxd210Y3ZodXl2Z3VnY3RiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzOTc2MDIsImV4cCI6MjA2MTk3MzYwMn0.9icPTMjJnlgpWIOX8Gjf6iwf-0RgVEoy7zmoJVqzHXc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);